### ISSUE TITLE
objstat

### ISSUE THREAD

**Issue by ab08028** [CMPG/polysel#1]
Hi Josephine,
Thanks for such a clear and comprehensive set of scripts! I'm really excited to try your method on my data. I am setting up my initial files and was wondering whether the objstat for each gene is the delta lnL or the delta lnL4 (fourth root)? It looks like it should be lnL4, but I just wanted to double-check. Thank you!

~ Annabel

**Comment by jdaub** [comment]
Hi Annabel,

Thank you for your interest in our method!
Yes, you are right: the objstat value for the 'primates' project is the fourth root of delta lnL.
I have now changed the example htmls, so that for each project it is clear what objStat represents.

**Comment by zuodabin** [comment]
Hi Josephine,
Thank you very much for your script. Now I want to run this script with my own data, but I want to replace gene score with K value in the output result of relax software, so which columns of input file in the script should I modify?
![Uploading 1700638027361.png…]()

**Comment by zuodabin** [comment]
![Uploading 1700638027361.png…]()

**Comment by jdaub** [comment]
Hi zuodabin,

I am not familiar with the K value in the relax software, but if this value is a score per gene, you can store it in the column objStat in the ObjInfo table. I recommend to investigate the properties of the K value in your data set (how is it distributed?) as described in one of the examples on our github page (https://htmlpreview.github.io/?https://github.com/CMPG/polysel/blob/master/example_humanpops.html)
