### ISSUE TITLE
Input for the Program

### ISSUE THREAD

**Issue by Rya-Stark** [CMPG/polysel#3]
Hi,

 Can you elaborate on how the input file is generated for species other than the ones provided in the example?

**Comment by jdaub** [comment]
Dear Rya-Stark,

Thank you for your interest in using polysel!

Polysel needs several input files (**SetInfo.txt,** **ObjInfo.txt** and **SetObj.txt**), so I am not sure which file you mean. Below I will describe the steps we took to get our data. I hope this will help.

1) To create **SetInfo.txt** for our projects, we downloaded the data from the NCBI Biosystems database (https://www.ncbi.nlm.nih.gov/biosystems/ ). 
We used the search string: "Homo sapiens"[Organism] AND "pathway"[BioSystemType] and choose send to: CSV file.

This database also contains gene set information from other species than humans. If your species of interest (or a related species) is in this databases, you can change the search replacing “Homo sapiens” with another species. 
You could also use species-specific databases, such as FlyBase (flybase.org) for D. melanogaster.

2) We downloaded gene information to create **ObjInfo.txt** from the NCBI Gene database (http://www.ncbi.nlm.nih.gov/gene/). We used the search string: "alive"[Properties] AND “homo sapiens"[Organism]  AND "genetype protein coding"[Properties] and choose Send to: file, format: Tabular, sort by Chromosome. Next, we filtered the downloaded file on tax_id = 9606 (removing Neanderthal data etc.) and on chromosome (1-22, X, Y). 

Again, you can find genes from other species in the NCBI gene data base, by replacing “homo sapiens” with the name of another species.
If you use gene set and gene information from a related species, you need to find the orthologues of the genes in this species that belong to your species of interest. You could use orthoDB for that (https://www.orthodb.org/)

The gene table was merged with the scores from our selection tests. If the scores were SNP based, we assigned each SNP to closest gene within 50 Kb and per gene took the SNP with highest z-value. 

3) To create **SetObj.txt***, go to ftp://ftp.ncbi.nih.gov/pub/biosystems/, choose CURRENT and download and unzip biosystems_gene.gz. This file contains a table with all biosystem – gene combinations. Filter this table on BSIDs that are in the SetInfo table.

**Comment by Rya-Stark** [comment]
Thank you so much. This was exactly what we were looking for. We are working our data now.
